modLoader="javafml"
loaderVersion="[49,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Api/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-api"

[modproperties.${mod_id}]
    catalogueImageIcon="catalogue_icon.png"
    catalogueBackground="catalogue_background.png"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},1.21)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"